# Generated by Django 6.0.1 on 2026-02-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('base_asset', models.CharField(max_length=20)),
                ('quote_asset', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api_keys.apikey')),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wallets.sleeve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SleeveStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('buy_quiet', 'Quiet Buy (conservative/longterm)'), ('sell_quiet', 'Quiet Sell (conservative/longterm)'), ('buy_flash', 'Flash Buy (aggressive/shortterm)'), ('sell_flash', 'Flash Sell (aggressive/shortterm)')], max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='wallets.sleeve')),
            ],
            options={
                'ordering': ['sleeve', 'mode'],
                'unique_together': {('sleeve', 'mode')},
            },
        ),
    ]
