# Generated by Django 6.0.1 on 2026-02-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_confidence',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_cooldown_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_entry_drop_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_last_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_pair',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_position_size_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_status',
            field=models.CharField(default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_stop_loss_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_take_profit_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
