# Generated by Django 6.0.1 on 2026-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_sleevestrategy_ml_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_last_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
