# Generated by Django 6.0.1 on 2026-02-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_sleevestrategy_ml_last_action_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleevestrategy',
            name='ml_candles_1h',
            field=models.IntegerField(default=0),
        ),
    ]
