# Generated by Django 6.0.1 on 2026-02-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_sleevestrategy_ml_candles_1h'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCandidatesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(default='USD', max_length=10)),
                ('items', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
