# Generated by Django 6.0.1 on 2026-02-16 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_profitcandidatescache"),
    ]

    operations = [
        migrations.CreateModel(
            name="MlMarketSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_snapshots",
                        to="trading.sleevestrategy",
                    ),
                ),
                ("pair", models.CharField(max_length=20)),
                ("lookback_days", models.IntegerField(default=0)),
                ("candles", models.IntegerField(default=0)),
                ("closes", models.JSONField(blank=True, default=list)),
                ("price_now", models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
