# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_mlmarketsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_stage",
            field=models.CharField(default="idle", max_length=30),
        ),
    ]
