# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0007_sleevestrategy_ml_stage_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlog",
            name="txid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
