# Generated by Django 6.0.1 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0008_orderlog_txid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_tick_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_price",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_entry_trigger",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_tp_trigger",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="sleevestrategy",
            name="ml_last_sl_trigger",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
