"""
Django settings for krakenv3 project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": str(BASE_DIR / "django_cache"),
    }
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b_ru-7&=)kor6g6q&x&$pa%d7fklevq4x88%)zs&4_v9b22&7i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'api_keys',
    'wallets',
    'trading.apps.TradingConfig',
    'django_huey',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'krakenv3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'krakenv3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Huey schedules (admin-adjustable via env)
ML_REFRESH_INTERVAL_MIN = int(os.environ.get('ML_REFRESH_INTERVAL_MIN', '5'))
EXECUTOR_INTERVAL_MIN = int(os.environ.get('EXECUTOR_INTERVAL_MIN', '2'))

EXECUTOR_TICK_SECONDS = int(os.environ.get('EXECUTOR_TICK_SECONDS', '1'))
EXECUTOR_BUY_TICK_SECONDS = int(os.environ.get('EXECUTOR_BUY_TICK_SECONDS', '4'))
EXECUTOR_SELL_TICK_SECONDS = int(os.environ.get('EXECUTOR_SELL_TICK_SECONDS', '1'))

EXECUTOR_BUY_TICK_SECONDS_FLASH = int(os.environ.get('EXECUTOR_BUY_TICK_SECONDS_FLASH', '4'))
EXECUTOR_SELL_TICK_SECONDS_FLASH = int(os.environ.get('EXECUTOR_SELL_TICK_SECONDS_FLASH', '1'))
EXECUTOR_BUY_TICK_SECONDS_QUIET = int(os.environ.get('EXECUTOR_BUY_TICK_SECONDS_QUIET', '15'))
EXECUTOR_SELL_TICK_SECONDS_QUIET = int(os.environ.get('EXECUTOR_SELL_TICK_SECONDS_QUIET', '5'))

ML_CONFIDENCE_MIN_QUIET = float(os.environ.get('ML_CONFIDENCE_MIN_QUIET', '0.90'))
ML_CONFIDENCE_MIN_FLASH = float(os.environ.get('ML_CONFIDENCE_MIN_FLASH', '0.55'))

ML_PRICE_TICK_SECONDS = int(os.environ.get('ML_PRICE_TICK_SECONDS', '5'))

# ML lookback window (smaller = faster refresh; still uses latest ticker + newest candles)
ML_LOOKBACK_DAYS = int(os.environ.get('ML_LOOKBACK_DAYS', '365'))

# Mode-specific lookbacks (defaults: quiet=30d, flash=7d). If unset, they fall back to ML_LOOKBACK_DAYS.
ML_LOOKBACK_DAYS_QUIET = int(os.environ.get('ML_LOOKBACK_DAYS_QUIET', '30'))
ML_LOOKBACK_DAYS_FLASH = int(os.environ.get('ML_LOOKBACK_DAYS_FLASH', '7'))

# Rolling candle storage retention for MlCandle (hours are stored, old rows are pruned).
ML_CANDLE_KEEP_DAYS = int(os.environ.get('ML_CANDLE_KEEP_DAYS', '30'))

# django-huey expects DJANGO_HUEY; provide HUEY alias for compatibility
DJANGO_HUEY = {
    'default': 'default',
    'queues': {
        'default': {
            'name': 'krakenv3',
            'huey_class': 'huey.SqliteHuey',
            'filename': str(BASE_DIR / 'huey.db'),
            'immediate': False,
            'consumer': {
                'workers': 1,
                'worker_type': 'thread',
            },
        },
    },
}
HUEY = DJANGO_HUEY

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '60/min',
        'anon': '10/min',
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

AUTH_USER_MODEL = 'accounts.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

