# Generated by Django 6.0.1 on 2026-02-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('DAI', 'DAI'), ('USDP', 'USDP')], max_length=10)),
                ('real_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('tradeable_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'currency'],
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quiet', 'Quiet'), ('flash', 'Flash')], max_length=10)),
                ('allocated_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeves', to='wallets.wallet')),
            ],
            options={
                'ordering': ['wallet', 'type'],
                'unique_together': {('wallet', 'type')},
            },
        ),
    ]
