# Generated by Django 6.0.1 on 2026-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeve',
            name='base_asset',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
