# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_sleeve_base_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleeve",
            name="trade_mode",
            field=models.CharField(choices=[("auto", "Auto"), ("custom", "Custom")], default="auto", max_length=10),
        ),
    ]
