# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_sleeve_trade_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleeve",
            name="position_base_qty",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=18),
        ),
    ]
