# Generated by Django 6.0.1 on 2026-02-16 00:00

from django.db import migrations


def forwards(apps, schema_editor):
    Sleeve = apps.get_model("wallets", "Sleeve")
    # Legacy bad normalization: some rows may contain BT instead of XBT.
    Sleeve.objects.filter(base_asset="BT").update(base_asset="XBT")


def backwards(apps, schema_editor):
    Sleeve = apps.get_model("wallets", "Sleeve")
    Sleeve.objects.filter(base_asset="XBT").update(base_asset="BT")


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_sleeve_position_base_qty"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
