# Generated by Django 6.0.1 on 2026-02-09 01:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.CharField(max_length=16)),
                ('quote_asset', models.CharField(max_length=16)),
                ('total_coins', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tradeable_coins', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('quiet_allocation', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('flash_allocation', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('paused', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sleeve_type', models.CharField(choices=[('quiet', 'Quiet'), ('flash', 'Flash')], max_length=16)),
                ('allocated_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit_retained', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('profit_returned', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('mode', models.CharField(default='manual', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeves', to='vaults.corevault')),
            ],
            options={
                'unique_together': {('vault', 'sleeve_type')},
            },
        ),
        migrations.CreateModel(
            name='BotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_runs_started', to=settings.AUTH_USER_MODEL)),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_runs_stopped', to=settings.AUTH_USER_MODEL)),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_runs', to='vaults.sleeve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tradeable_remaining', models.DecimalField(decimal_places=8, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to='vaults.corevault')),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_history', to='vaults.sleeve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('asset', models.CharField(max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='corevault',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='core_vaults', to='vaults.wallet'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=64)),
                ('exchange', models.CharField(default='kraken', max_length=32)),
                ('key_encrypted', models.TextField()),
                ('secret_encrypted', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('rotation_index', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'label')},
            },
        ),
    ]
