# Generated by Django 6.0.1 on 2026-02-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='health_status',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='corevault',
            name='allow_zero_tradeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corevault',
            name='max_daily_loss_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='corevault',
            name='max_drawdown_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='corevault',
            name='max_position_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='corevault',
            name='reserve_buffer_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='corevault',
            name='trading_window',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sleeve',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sleeve',
            name='expected_return',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sleeve',
            name='regime',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
