# Generated by Django 6.0.1 on 2026-02-09 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0003_approvalrequest_auditlog_keyrotationevent_pauseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleevePnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_snapshots', to='vaults.sleeve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaultPnl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('unrealized', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnl_snapshots', to='vaults.corevault')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
