# Generated by Django 6.0.1 on 2026-02-10 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0004_sleevepnl_vaultpnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(default='open', max_length=16)),
                ('exchange_order_id', models.CharField(blank=True, max_length=128)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('fees', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vaults.sleeve')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.CharField(max_length=16)),
                ('quote', models.CharField(max_length=16)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'quote', 'timestamp'], name='vaults_pric_asset_75896f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='vaults.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
