# Generated by Django 6.0.1 on 2026-02-11 00:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0005_order_pricesnapshot_tradefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevault',
            name='allowed_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corevault',
            name='fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.004'), max_digits=6),
        ),
        migrations.AddField(
            model_name='corevault',
            name='slippage_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.001'), max_digits=6),
        ),
    ]
