# Generated by Django 6.0.1 on 2026-02-11 01:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0006_corevault_allowed_pairs_corevault_fee_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='vaults.sleeve')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
