# Generated by Django 6.0.1 on 2026-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0007_strategydecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeve',
            name='flash_principal',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
